---
kind: pipeline
name: ts3build

steps:
  - name: hadolint
    #image: hadolint/hadolint:latest-debian
    image: "ghcr.io/hadolint/hadolint:latest-debian"
    commands:
      - hadolint --version
      - hadolint  Dockerfile
  - name: build master
    image: plugins/docker
    settings:
      repo: sunna.nbg:5050/teamspeak
      registry: sunna.nbg:5050
      autotag: yes
      insecure: yes
    when:
      event:
        - tag
        - push