---
kind: pipeline
name: ts3build

platform:
  os: linux
  arch: amd64

steps:
  - name: hadolint
    #image: hadolint/hadolint:latest-debian
    image: "ghcr.io/hadolint/hadolint:latest-debian"
    commands:
      - hadolint --version
      - hadolint Dockerfile
      - hadolint Dockerfile.alpine
  - name: build master
    image: plugins/docker
    settings:
      repo: sunna.nbg:5050/teamspeak
      registry: sunna.nbg:5050
      autotag: yes
      insecure: yes
    when:
      event:
        - tag
        - push
  - name: build tag
    image: plugins/docker
    settings:
      repo: sunna.nbg:5050/teamspeak
      registry: sunna.nbg:5050
      autotag: yes
      insecure: yes
    when:
      event:
        - tag
  - name: build alpine
    image: plugins/docker
    settings:
      repo: sunna.nbg:5050/teamspeak
      registry: sunna.nbg:5050
      autotag: no
      insecure: yes
      dockerfile: Dockerfile.alpine
      tags:
        - alpine
    when:
      event:
        - push
  - name: build alpine release
    image: plugins/docker
    settings:
      repo: sunna.nbg:5050/teamspeak
      registry: sunna.nbg:5050
      autotag: no
      insecure: yes
      dockerfile: Dockerfile.alpine
      default_suffix: alpine
      tags:
        - ${DRONE_TAG}
    when:
      event:
        - tag
